#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Embed the dependency-free phone page directly in the firmware flash."""
from pathlib import Path
ROOT = Path(__file__).resolve().parents[2]
folder = Path(__file__).with_name("phone")
html = (folder / "index.html").read_text(encoding="utf-8")
for name in ("core.js", "app.js"):
    code = (folder / name).read_text(encoding="utf-8")
    assert "</script" not in code.lower()
    html = html.replace(f'<script src="{name}"></script>', f"<script>\n{code}\n</script>")
assert ")P36PAGE\"" not in html
output = ROOT / "firmware/portrait36/include/phone_page.h"
output.write_text('// SPDX-License-Identifier: MIT\n// Generated by tools/portrait_display/build_phone_page.py\n'
                  '#pragma once\n#include <pgmspace.h>\nnamespace epd36 {\n'
                  'static const char kPhoneIndexHtml[] PROGMEM = R"P36PAGE(' + html + ')P36PAGE";\n}\n', encoding="utf-8")
print(f"{output}: {len(html.encode('utf-8'))} UTF-8 bytes, no remote assets")
