[env:portrait36-c3]
platform = espressif32@7.1.3
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
build_flags =
  -I../include
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MSC_ON_BOOT=0
board_build.flash_mode = qio
board_build.flash_size = 4MB
