"""Inventory 3D model paths on badge.kicad_pcb. STEP CLI return 0 is not coverage.

J3 and J2 use repo envelope STEP files generated by make_envelope_3d.py.
Those envelopes are occupancy placeholders, not vendor CAD. Official KiCad 9.0.8
has JST SH (SRSS-TB), not SHL/SHLS-TF — do not substitute.
"""
import argparse
import json
import os
import re
import shutil
import sys
from pathlib import Path

p = argparse.ArgumentParser()
p.add_argument("--pcb-dir", default=os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
p.add_argument("--json-out", default="")
p.add_argument("--fail-missing", action="store_true",
               help="exit 1 if any referenced model file is missing (release gate)")
a = p.parse_args()
pcb_dir = Path(a.pcb_dir).resolve()
board = pcb_dir / "badge.kicad_pcb"
text = board.read_text(encoding="utf-8", errors="replace")
cli = shutil.which("kicad-cli") or shutil.which("kicad-cli.exe")
share_3d = os.environ.get("KICAD9_3DMODEL_DIR", "")
if not share_3d and cli:
    bindir = Path(cli).resolve().parent
    cand = bindir.parent / "share" / "kicad" / "3dmodels"
    if cand.is_dir():
        share_3d = str(cand)
env = {
    "KIPRJMOD": str(pcb_dir),
    "KICAD9_3DMODEL_DIR": share_3d,
    "KICAD8_3DMODEL_DIR": os.environ.get("KICAD8_3DMODEL_DIR", ""),
    "KICAD10_3DMODEL_DIR": os.environ.get("KICAD10_3DMODEL_DIR", ""),
}
models = []
for raw in re.findall(r'\(model\s+"([^"]+)"', text):
    resolved = raw
    for key, val in env.items():
        resolved = resolved.replace("${" + key + "}", val)
    path = Path(resolved)
    alts = [path]
    for ext in (".step", ".stp", ".STEP", ".wrl"):
        alts.append(path.with_suffix(ext))
    exists = any(x.is_file() for x in alts)
    models.append({"raw": raw, "resolved": str(path), "exists": exists})
# Unique by resolved path, keep first.
uniq, seen = [], set()
for m in models:
    if m["resolved"] in seen:
        continue
    seen.add(m["resolved"])
    uniq.append(m)
missing = [m for m in uniq if not m["exists"]]
j2_expected = "JST_SHL_SM02B-SHLS-TF_1x02-1MP_P1.00mm_Horizontal.step"
j2_dir = Path(share_3d) / "Connector_JST.3dshapes" if share_3d else None
nearby = []
if j2_dir and j2_dir.is_dir():
    nearby = sorted(x.name for x in j2_dir.iterdir() if "SM02B" in x.name or "SHL" in x.name)
notes = [
    "J3: ${KIPRJMOD}/lib/3d/TYPE-C-31-M-14.step is a mechanical envelope "
    "(make_envelope_3d.py), not HRO official CAD. STEP CLI rc=0 is not coverage.",
    "J2: ${KIPRJMOD}/lib/3d/" + j2_expected
    + " is a SHL envelope; KiCad 9.0.8 has SH (SRSS-TB) only — do not substitute. "
    "Nearby official SM02B files: " + (", ".join(nearby) if nearby else "(none / dir missing)"),
    "ESP32 model: ${KIPRJMOD}/lib/3d/ESP32-C3-MINI-1.STEP (vendor STEP, present).",
]
data = {
    "kicad9_3dmodel_dir": share_3d,
    "unique_models": len(uniq),
    "missing_count": len(missing),
    "missing": missing,
    "all": uniq,
    "notes": notes,
    "step_cli_zero_is_not_coverage": True,
}
if a.json_out:
    Path(a.json_out).write_text(json.dumps(data, indent=2), encoding="utf-8")
print(json.dumps({
    "unique_models": len(uniq),
    "missing_count": len(missing),
    "missing": [{"raw": m["raw"], "resolved": m["resolved"]} for m in missing],
    "notes": notes,
}, indent=2))
if a.fail_missing and missing:
    sys.exit(1)
